export const AUTH_REQ = 'AUTH_REQ';
export const AUTH_REQ_SUCCESS = 'AUTH_REQ_SUCCESS';
export const AUTH_REQ_FAILURE = 'AUTH_REQ_FAILURE';

export const LOGIN_REQ_SUCCESS = 'LOGIN_REQ_SUCCESS';
export const LOGOUT_REQ_SUCCESS = 'LOGOUT_REQ_SUCCESS';
export const UPDATE_PROFILE = 'UPDATE_PROFILE';
export const GET_SINGLE_PROFILE = 'GET_SINGLE_PROFILE';

export const VERIFY_OTP_SUCCESS = 'VERIFY_OTP_SUCCESS';

export const VERIFY_FORGET_OTP = 'VERIFY_FORGET_OTP';

export const FORGET_PASSWORD = 'FORGET_PASSWORD';

export const CHANGE_PASSWORD = 'CHANGE_PASSWORD';