
export const DOUBT_REQ = 'DOUBT_REQ';
export const DOUBT_REQ_SUCCESS = 'DOUBT_REQ_SUCCESS';
export const DOUBT_FAILURE = 'DOUBT_FAILURE';

export const POST_DOUBT_SUCCESS = 'POST_DOUBT_SUCCESS';

export const DELETE_DOUBT_SUCCESS = 'DELETE_DOUBT_SUCCESS';

export const UPDATE_DOUBT_SUCCESS = 'UPDATE_DOUBT_SUCCESS';


